# Generated by Django 4.0.2 on 2022-02-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
